import type { Metadata } from 'next';
import {
  AppBar,
  Container,
  Button,
  Box,
  Toolbar,
  Typography,
} from '@mui/material';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import { Open_Sans } from 'next/font/google';
import theme from '@/theme';
import { NextLinkComposed } from '@components/LinkAdapter';

const openSans = Open_Sans({
  weight: ['800'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'VGM Obscura Dashboard',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>
          <CssBaseline />
          <AppBar position="static">
            <Container maxWidth="xl" disableGutters>
              <Toolbar disableGutters>
                <Typography
                  variant="h5"
                  component="h1"
                  sx={{
                    fontFamily: openSans.style.fontFamily,
                    fontWeight: 800,
                    p: '1rem',
                  }}
                >
                  VGM Obscura Stats
                </Typography>
                <Box sx={{ ml: '1rem' }}>
                  <Button component={NextLinkComposed} to="/">
                    Overview
                  </Button>
                  <Button component={NextLinkComposed} to="/charts">
                    Charts
                  </Button>
                </Box>
              </Toolbar>
            </Container>
          </AppBar>
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}
